---
#- name: ARTACK | C3 | Check for composer.phar
#  stat: path={{symfony_composer_path}}
#  register: composer_file
#
#- name: ARTACK | C3 | Run composer self-update
#  shell: "{{symfony_composer_path}} selfupdate --no-interaction"
#  when: composer_file.stat.exists and symfony_composer_self_update|bool
#  register: composer_self_update_result
#  changed_when: composer_self_update_result.stderr is search('Updating')
#
#- name: ARTACK | C3 | Install stable composer
#  get_url: url=https://getcomposer.org/composer-stable.phar dest={{symfony_composer_path}} mode=0755 validate_certs=no force=no
#  when: symfony_composer_version is not defined
#
#- name: ARTACK | C3 | Install composer {{symfony_composer_version}}
#  get_url: url=https://getcomposer.org/download/{{symfony_composer_version}}/composer.phar dest={{symfony_composer_path}} mode=0755 validate_certs=no force=no
#  when: symfony_composer_version is defined

- name: ARTACK | C3 | Run composer install (contao composer - 1st)
  shell: chdir={{ansistrano_release_path.stdout}}
    export SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} && {{symfony_php_path}} {{symfony_composer_path}} install {{symfony_composer_options}} -d composer
  register: composer_install_result
  changed_when: composer_install_result.stderr is search('- \w+ing ')
  ignore_errors: yes

- name: ARTACK | C3 | Run composer install (contao composer - 2st)
  shell: chdir={{ansistrano_release_path.stdout}}
    export SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} && {{symfony_php_path}} {{symfony_composer_path}} install {{symfony_composer_options}} -d composer
  register: composer_install_result
  changed_when: composer_install_result.stderr is search('- \w+ing ')
